# cloudbuild.yaml

steps:
- name: gcr.io/cloud-builders/docker
  id: 'cloudbuild-android'
  env:
    - 'BUILD=$BUILD_ID'
    - 'PROJECT=$PROJECT_ID'
    - 'REV=$REVISION_ID'
  args: [
    'build',
    '-t', 'eu.gcr.io/$PROJECT_ID/cloudbuild-android:${SHORT_SHA}',
    '-t', 'eu.gcr.io/$PROJECT_ID/cloudbuild-android:latest',

    # These are used by Cloud Build variable substitutions (as shown in screenshot_01.png):
    # https://cloud.google.com/cloud-build/docs/configuring-builds/substitute-variable-values
    #'--build-arg', 'ANDROID_SDK_PACKAGES="${_ANDROID_SDK_PACKAGES"}',
    #'--build-arg', 'GRADLE_WRAPPER_VERSION=${_GRADLE_WRAPPER_VERSION}',

    # By default these static values are being used, without the NDK (build-trigger configuration not required.
    # Note: When commenting these out, one has to run `./gradlew build` to fetch the components instead.
    # '--build-arg', 'ANDROID_SDK_PACKAGES=platform-tools platforms;android-34 build-tools;34.0.0 ndk;23.1.7779620',
    '--build-arg', 'ANDROID_SDK_PACKAGES=platform-tools platforms;android-34 build-tools;34.0.0',
    '--build-arg', 'GRADLE_WRAPPER_VERSION=8.0',

    # enable cloudbuild network
    '--network', 'cloudbuild',
    '.'
  ]

images:
- 'eu.gcr.io/$PROJECT_ID/cloudbuild-android:${SHORT_SHA}'
- 'eu.gcr.io/$PROJECT_ID/cloudbuild-android:latest'
options: 
- logging: CLOUD_LOGGING_ONLY

